### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by szylhh** [Womsxd/xixunyun-sign#5]
大佬好，运行报错： python main.py 
  File "main.py", line 27
    def get_day() -> str:
                  ^
SyntaxError: invalid syntax

 python 版本：2.7

**Comment by szylhh** [comment]
python报错是下面这样，[root@instance-20220904-1351 xixunyun-sign-master]# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'

**Comment by Womsxd** [comment]
py版本最低要求3.6

**Comment by Womsxd** [comment]
> python报错是下面这样，[root@instance-20220904-1351 xixunyun-sign-master]# python3 main.py Traceback (most recent call last): File "main.py", line 8, in import rsa ModuleNotFoundError: No module named 'rsa'

解决办法 pip3 install -r requirements.txt

**Comment by szylhh** [comment]
好的大佬成功，这个推送怎么选择？
![image](https://user-images.githubusercontent.com/12439721/188567173-a9a7daff-11f5-47f3-a18e-94387166cc0c.png)

**Comment by szylhh** [comment]
![image](https://user-images.githubusercontent.com/12439721/188576981-fccb0420-d454-495b-bf93-7bbf22d73401.png)
大佬，是不是这样呢？我是要用pushplus

**Comment by Womsxd** [comment]
> ![image](https://user-images.githubusercontent.com/12439721/188576981-fccb0420-d454-495b-bf93-7bbf22d73401.png) 大佬，是不是这样呢？我是要用pushplus

是

**Comment by szylhh** [comment]
好的，谢谢大佬

**Comment by Womsxd** [comment]
你要更多push选项的话可以拿
https://github.com/Womsxd/AutoMihoyoBBS/blob/master/push.py
这里的push（
我后续搬运一下
