### ISSUE TITLE
你好，我想知道地址如何加密的

### ISSUE THREAD

**Issue by yunmangmeng** [Womsxd/xixunyun-sign#6]
rsa_public_key = "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlYsiV3DsG" \
                 "+t8OFMLyhdmG2P2J4GJwmwb1rKKcDZmTxEphPiYTeFIg4IFEiqDCA" \
                 "TAPHs8UHypphZTK6LlzANyTzl9LjQS6BYVQk81LhQ29dxyrXgwkRw9RdWa" \
                 "MPtcXRD4h6ovx6FQjwQlBM5vaHaJOHhEorHOSyd/deTvcS+hRSQIDAQAB\n-----END PUBLIC KEY-----"
def public_encrypt(raw_data):
    pub_key = rsa.PublicKey.load_pkcs1_openssl_pem(rsa_public_key)
    base46_enc = base64.b64encode(rsa.encrypt(raw_data.encode('utf-8'), pub_key))
    return base46_enc.decode('utf-8')
这是从哪里抓包找到的吗

**Comment by Womsxd** [comment]
逆向apk，现在不知道换了没

**Comment by yunmangmeng** [comment]
> 逆向apk，现在不知道换了没

我找到了，没有换
